### ISSUE TITLE
Money splitting should return values in proper payable amount

### ISSUE THREAD

**Issue by davis12529** [oswellchan/whopaybot#1]
**Problem**
 Currently the bot returns amount in 4 decimal places (e.g $10.1234). It should return an payable amount ($10.12) such that the payee will not lose or gain extra cents i.e some of the payers would pay 1 cent more than others. Example: $10/6 = 4*$1.67 + 2*$1.66.

**Solution**
Find the remainder of `amount`/`payers` and split up the remainder among the payers randomly.

Pros
- Payee will get the exact amount owed.

Cons
- In cases of division with remainder, some payers will pay at most 1 cent more than the rest (by luck)

**Comment by oswellchan** [comment]
Okay. I think this is a valid solution. We can implement this.

**Comment by oswellchan** [comment]
Sometimes, the bill will be off by a few cents because of rounding off of `tax * full_bill_amount` vs `tax * single_item_amount`: Extra 0.00XX removed by rounding off can end up adding to 1 cent.

But behaviour is acceptable for the convenience. Users can offer to pay off the remaining 1++ cents.
